### ISSUE TITLE
OCR For PS4Macro

### ISSUE THREAD

**Issue by baggypants71** [leguims/PS4Macro.PES2018Lite#8]
Hi Leguims, 

I accidentally closed the last thread. Is it be possible to incorporate an OCR into this library instead of using the picture recognition?. How difficult would it be to do?. I am making progress with C# and my goal is to eventually understand enough to do it myself.

**Comment by baggypants71** [comment]
Is it possible to randomize the time for the Sleep method?. I want to have a sleep range from 1-3 seconds per dualshock state. 

Any help would be most appreciated

**Comment by leguims** [comment]
Look at this : [how do i generate a random int number](https://stackoverflow.com/questions/2706500/how-do-i-generate-a-random-int-number)

**Comment by leguims** [comment]
@baggypants71 it is reopen.

For OCR, it is a good Idea, but I can't help you.

I already thought about this, but never do it. [OCR for PS4Macro](https://github.com/komefai/PS4Macro/issues/11)

Good Luck, this is a major enhance.

**Comment by baggypants71** [comment]
I was looking at the Library Tesseract which also requires also requires the training data. I agree with you that it would be an excellent enhancement. I believe we both think alike except you are better at C# than me!. We have a saying in English/Austalian "Great minds think alike"

**Comment by leguims** [comment]
In french : "Les grands esprits se rencontrent"

**Comment by baggypants71** [comment]
I haven't been to France for over 15 years, I moved to Australia over 10 years from the UK. I can speak fluent German & get by in French. Like most people, I love the French accent!. Your national football team is quite good too!.

**Comment by leguims** [comment]
If you love french accent, I still have when I try to speak english. French team is good, but Paris losed against Manchester, so bad day.
If you want, you can speak french on your issue. :)

**Comment by baggypants71** [comment]
I Saw the PSG v ManUtd game, good game, I wanted to see more from Mbeppe!, what a gifted player!. I support  West Bromwich Albion who are in the league below the English Premiership. 

As for typing French, I would not be very good, I can speak it better than typing it. Your English is excellent. bonne nuit mon ammi!
