### ISSUE TITLE
R2-L2 Press?

### ISSUE THREAD

**Issue by baggypants71** [leguims/PS4Macro.PES2018Lite#9]
@leguims, Sorry for bothering you again, could you tell me how I get the DuelShockState to press R2 - L2?

```
script.Press(new DualShockState() { R2 = true });
```
I get a red error under true when I ask it to press R2 or L2. should the true be a value?....

**Comment by baggypants71** [comment]
Yes is a value R2 or L2 = 255

**Comment by leguims** [comment]
You Can probably presse R2/L2 in range [0 , 255]. Analog Button.

**Comment by baggypants71** [comment]
> 
> 
> You Can probably presse R2/L2 in range [0 , 255]. Analog Button.

You are correct, I figured this one out with trial; and error. :)

**Comment by baggypants71** [comment]
@leguims , Are you from France? or should I say Parlez-vous français ?

**Comment by leguims** [comment]
Yes, I am.
